dynaconf_merge = true

[default]
    SECRET_KEY = "django-insecure-6fwggv-psx!--(4d%a0y(gc+#n(^urxzxhs)l++^y1b*arh$!a"
    

[development]
    SECRET_KEY = "django-insecure-6fwggv-psx!--(4d%a0y(gc+#n(^urxzxhs)l++^y1b*arh$!a"


[test]
    SECRET_KEY = "django-insecure-6fwggv-psx!--(4d%a0y(gc+#n(^urxzxhs)l++^y1b*arh$!a"


[production]
    SECRET_KEY = "django-insecure-6fwggv-psx!--(4d%a0y(gc+#n(^urxzxhs)l++^y1b*arh$!a"
